show USER;
SELECT TO_CHAR(LAST_NUMBER, 'FM99999999999999999') AS LAST_NUMBER FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'GET_NEXT_ORDER_NUMBER_SEQ';
ALTER SEQUENCE GET_NEXT_ORDER_NUMBER_SEQ INCREMENT BY 150000;
commit;
ALTER SEQUENCE GET_NEXT_ORDER_NUMBER_SEQ INCREMENT BY 1;
commit;
SELECT TO_CHAR(LAST_NUMBER, 'FM99999999999999999') AS LAST_NUMBER FROM ALL_SEQUENCES WHERE SEQUENCE_NAME = 'GET_NEXT_ORDER_NUMBER_SEQ';
exit;
