show USER;
Alter table ODI_TMP."E$_Notification_EMAIL_SMS" add CONTRACT_FLAGS NUMBER(1) ;
Alter table ODI_TMP."E$_Notification_EMAIL_SMS" add RENEW_FLAGS NUMBER(1)  ;


Alter table odi_tmp."E$_VF_INVOICE_ODI_SHARED_T" add CONTRACT_FLAGS NUMBER(1) ;
Alter table odi_tmp."E$_VF_INVOICE_ODI_SHARED_T" add RENEW_FLAGS NUMBER(1)  ;


ALTER TABLE "ODI_TMP"."E$_VF_INVOICE_ODI_SHARED_T" ADD CREAM_COLOR_BG VARCHAR2(1);
ALTER TABLE "ODI_TMP"."E$_VF_INVOICE_ODI_SHARED_T" ADD CREAM_COLOR_BG_LARGE_FONT VARCHAR2(1);

ALTER TABLE "ODI_TMP"."E$_MERGING_PAPER_DOM" ADD CREAM_COLOR_BG VARCHAR2(1);
ALTER TABLE "ODI_TMP"."E$_MERGING_PAPER_DOM" ADD CREAM_COLOR_BG_LARGE_FONT VARCHAR2(1);

ALTER TABLE "ODI_TMP"."E$_MERGING_NOPAPER_DOM" ADD CREAM_COLOR_BG VARCHAR2(1);
ALTER TABLE "ODI_TMP"."E$_MERGING_NOPAPER_DOM" ADD CREAM_COLOR_BG_LARGE_FONT VARCHAR2(1);

ALTER TABLE "ODI_TMP"."E$_MERGING_PAPER_INT" ADD CREAM_COLOR_BG VARCHAR2(1);
ALTER TABLE "ODI_TMP"."E$_MERGING_PAPER_INT" ADD CREAM_COLOR_BG_LARGE_FONT VARCHAR2(1);

ALTER TABLE "ODI_TMP"."E$_MERGING_NOPAPER_INT" ADD CREAM_COLOR_BG VARCHAR2(1);
ALTER TABLE "ODI_TMP"."E$_MERGING_NOPAPER_INT" ADD CREAM_COLOR_BG_LARGE_FONT VARCHAR2(1);


/* ALTER TABLE "ODI_TMP"."E$_VF_INVOICE_ODI_SHARED_T" DROP COLUMN CREAM_COLOR_BG; */
/* ALTER TABLE "ODI_TMP"."E$_VF_INVOICE_ODI_SHARED_T" DROP COLUMN CREAM_COLOR_BG_LARGE_FONT; */

/* ALTER TABLE "ODI_TMP"."E$_MERGING_PAPER_DOM" DROP COLUMN CREAM_COLOR_BG; */
/* ALTER TABLE "ODI_TMP"."E$_MERGING_PAPER_DOM" DROP COLUMN CREAM_COLOR_BG_LARGE_FONT; */

/* ALTER TABLE "ODI_TMP"."E$_MERGING_NOPAPER_DOM" DROP COLUMN CREAM_COLOR_BG; */
/* ALTER TABLE "ODI_TMP"."E$_MERGING_NOPAPER_DOM" DROP COLUMN CREAM_COLOR_BG_LARGE_FONT; */

/* ALTER TABLE "ODI_TMP"."E$_MERGING_PAPER_INT" DROP COLUMN CREAM_COLOR_BG; */
/* ALTER TABLE "ODI_TMP"."E$_MERGING_PAPER_INT" DROP COLUMN CREAM_COLOR_BG_LARGE_FONT; */

/* ALTER TABLE "ODI_TMP"."E$_MERGING_NOPAPER_INT" DROP COLUMN CREAM_COLOR_BG; */
/* ALTER TABLE "ODI_TMP"."E$_MERGING_NOPAPER_INT" DROP COLUMN CREAM_COLOR_BG_LARGE_FONT; */


/* drop table ODI_TMP.E$_MERGING_PAPER_DOM; */
/* drop table ODI_TMP.E$_MERGING_NOPAPER_DOM; */

