show USER;
CREATE TABLE "ODI_STAGING"."ODI_STG_ARUCS"
   (    "REFERENCE" VARCHAR2(18 CHAR),
        "TRANSACTION_CODE" VARCHAR2(2 CHAR),
        "RETURN_CODE" NUMBER(1,0),
        "RETURN_DESCRIPTION" VARCHAR2(24 CHAR),
        "UAC_NAME" VARCHAR2(12 CHAR),
        "VALUE_OF_ITEM" NUMBER(11,0),
        "CURRENCY" VARCHAR2(3 CHAR),
        "BENEFICIARY_ACCOUNT_NAME" VARCHAR2(18 CHAR),
        "RETURNING_SORT_CODE" VARCHAR2(8 CHAR),
        "RETURNING_ACCOUNT" NUMBER(8,0),
        "BANK_NAME" VARCHAR2(20 CHAR),
        "BANK_OFFICE_NAME" VARCHAR2(27 CHAR),
        "ACCNT_BU" VARCHAR2(100 CHAR),
        "LOC" VARCHAR2(50 CHAR),
        "NAME" VARCHAR2(100 CHAR),
        "PARTY_TYPE_CD" VARCHAR2(30 CHAR),
        "PARTY_UID" VARCHAR2(100 CHAR),
        "AI_ADDR_NAME" VARCHAR2(100 CHAR),
        "AI_NAME" VARCHAR2(100 CHAR),
        "LOAD_DATE" DATE,
        "SESS_NO" NUMBER(38,0),
        "FILENAME" VARCHAR2(100 BYTE),
        "BATCHNUM" NUMBER(10,0)
   );

ALTER TABLE ODI_STAGING.ODI_STG_ARUCS ADD TRADE_BACS_VAL_OF_ITEM NUMBER(22,7);


Alter table odi_staging."Notification_EMAIL_SMS" add CONTRACT_FLAGS NUMBER(1) ;
Alter table odi_staging."Notification_EMAIL_SMS" add RENEW_FLAGS NUMBER(1)  ;


Alter table odi_staging."VF_INVOICE_ODI_SHARED_T" add CONTRACT_FLAGS NUMBER(1) ;
Alter table odi_staging."VF_INVOICE_ODI_SHARED_T" add RENEW_FLAGS NUMBER(1)  ;


DROP SEQUENCE "ODI_STAGING"."FILESEQUENCEVALUE";
CREATE SEQUENCE  "ODI_STAGING"."FILESEQUENCEVALUE"  MINVALUE 8 MAXVALUE 9 INCREMENT BY 1 NOCACHE NOORDER  CYCLE ;


ALTER TABLE ODI_STAGING.ODI_STG_ARUCS DROP COLUMN RETURN_CODE;
ALTER TABLE ODI_STAGING.ODI_STG_ARUCS ADD RETURN_CODE VARCHAR2(1);

ALTER TABLE ODI_STG_ARUCS
MODIFY (VALUE_OF_ITEM NUMBER(22,7));



ALTER TABLE ODI_STAGING.VF_INVOICE_ODI_SHARED_T ADD CREAM_COLOR_BG VARCHAR2(1);
ALTER TABLE ODI_STAGING.VF_INVOICE_ODI_SHARED_T ADD CREAM_COLOR_BG_LARGE_FONT VARCHAR2(1);

ALTER TABLE ODI_STAGING.MERGING_PAPER_DOM ADD CREAM_COLOR_BG VARCHAR2(1);
ALTER TABLE ODI_STAGING.MERGING_PAPER_DOM ADD CREAM_COLOR_BG_LARGE_FONT VARCHAR2(1);

ALTER TABLE ODI_STAGING.MERGING_NOPAPER_DOM ADD CREAM_COLOR_BG VARCHAR2(1);
ALTER TABLE ODI_STAGING.MERGING_NOPAPER_DOM ADD CREAM_COLOR_BG_LARGE_FONT VARCHAR2(1);

ALTER TABLE ODI_STAGING.MERGING_PAPER_INT ADD CREAM_COLOR_BG VARCHAR2(1);
ALTER TABLE ODI_STAGING.MERGING_PAPER_INT ADD CREAM_COLOR_BG_LARGE_FONT VARCHAR2(1);

ALTER TABLE ODI_STAGING.MERGING_NOPAPER_INT ADD CREAM_COLOR_BG VARCHAR2(1);
ALTER TABLE ODI_STAGING.MERGING_NOPAPER_INT ADD CREAM_COLOR_BG_LARGE_FONT VARCHAR2(1);

/* ALTER TABLE ODI_STAGING.VF_INVOICE_ODI_SHARED_T DROP COLUMN CREAM_COLOR_BG; */
/* ALTER TABLE ODI_STAGING.VF_INVOICE_ODI_SHARED_T DROP COLUMN CREAM_COLOR_BG_LARGE_FONT; */

/* ALTER TABLE ODI_STAGING.MERGING_PAPER_DOM DROP COLUMN CREAM_COLOR_BG; */
/* ALTER TABLE ODI_STAGING.MERGING_PAPER_DOM DROP COLUMN CREAM_COLOR_BG_LARGE_FONT; */

/* ALTER TABLE ODI_STAGING.MERGING_NOPAPER_DOM DROP COLUMN CREAM_COLOR_BG; */
/* ALTER TABLE ODI_STAGING.MERGING_NOPAPER_DOM DROP COLUMN CREAM_COLOR_BG_LARGE_FONT; */

/* ALTER TABLE ODI_STAGING.MERGING_PAPER_INT DROP COLUMN CREAM_COLOR_BG; */
/* ALTER TABLE ODI_STAGING.MERGING_PAPER_INT DROP COLUMN CREAM_COLOR_BG_LARGE_FONT;*/

/* ALTER TABLE ODI_STAGING.MERGING_NOPAPER_INT DROP COLUMN CREAM_COLOR_BG;*/
/* ALTER TABLE ODI_STAGING.MERGING_NOPAPER_INT DROP COLUMN CREAM_COLOR_BG_LARGE_FONT;*/

/* drop table "ODI_STAGING"."MERGING_PAPER_DOM" */
/* drop table "ODI_STAGING"."MERGING_NOPAPER_DOM" */
